### ISSUE TITLE
Support for transparent color

### ISSUE THREAD

**Issue by guivr** [oceangravity/webskit-gradient-parser#19]
Hi, @oceangravity , first of all, thank you SO MUCH for this library!

I've noticed that it's not creating the correct "stops" when using the color name "transparent".
Example: `radial-gradient(ellipse farthest-corner at 100% 0, #893dc2, transparent 50%)`

**Comment by oceangravity** [comment]
Hey @guivr thanks! hmmm I'll check this 👁‍🗨
